version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: restx_sql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MatKhauManh!2025
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ../sqlserver/data:/var/opt/mssql
    networks:
      - restx-network

  api:
    image: tranvietthangdev/restx-api:latest
    env_file:
      - .env
    container_name: restx_api
    restart: always
    environment:
      - ConnectionStrings__RestX=Server=db,1433;Database=RestX_RestaurantManagement;User Id=sa;Password=MatKhauManh!2025;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://160.250.5.94:5000/
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - restx-network

  ui:
    image: tranvietthangdev/restx-ui:latest
    container_name: restx_ui
    restart: always
    environment:
      - ConnectionStrings__RestX=Server=db,1433;Database=RestX_RestaurantManagement;User Id=sa;Password=MatKhauManh!2025;TrustServerCertificate=True;
      - ApiSettings__BaseUrl=http://api:8080/
      - VnPaySettings__ReturnUrl=http://160.250.5.94/Staff/PaymentReturn
      - VnPaySettings__CancelUrl=http://160.250.5.94/Staff/PaymentCancel
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
    depends_on:
      - api
    networks:
      - restx-network

networks:
  restx-network:
    name: restx-network
    driver: bridge