version: '3.8'

services:
  # 1. Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: restx_sql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MatKhauManh!2025
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      # ✅ QUAN TRỌNG: Dùng .. để trỏ ra ngoài giữ lại dữ liệu cũ
      - ../sqlserver/data:/var/opt/mssql
    networks:
      - restx-network

  # 2. API Backend
  api:
    build:
      context: .
      dockerfile: RestX.API/Dockerfile
    container_name: restx_api
    restart: always
    environment:
      - ConnectionStrings__RestX=Server=db,1433;Database=RestX_RestaurantManagement;User Id=sa;Password=MatKhauManh!2025;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      # ✅ Ghi đè url API thành cổng 5000 (Public)
      - ApiSettings__BaseUrl=http://160.250.5.94:5000/
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - restx-network

  # 3. UI Frontend (MVC)
  ui:
    build:
      context: .
      dockerfile: RestX.UI/Dockerfile
    container_name: restx_ui
    restart: always
    environment:
      - ConnectionStrings__RestX=Server=db,1433;Database=RestX_RestaurantManagement;User Id=sa;Password=MatKhauManh!2025;TrustServerCertificate=True;
      # ✅ UI gọi API qua mạng nội bộ (Cổng 8080)
      - ApiSettings__BaseUrl=http://api:8080/
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
    depends_on:
      - api
    networks:
      - restx-network

networks:
  restx-network:
    name: restx-network
    driver: bridge